name: flutter_packages_remover
description: A command-line tool to find and remove unused packages from pubspec.yaml.
version: 1.0.0
homepage: https://github.com/ahmedelmwafy/flutter_packages_remover

environment:
  sdk: ">=2.18.0 <4.0.0"
  # flutter: ">=1.17.0" # This tool is a pure Dart package, Flutter SDK is not required for the tool itself

dependencies:
  analyzer: ^6.0.0 # To parse Dart code and find imports
  args: ^2.4.0      # To parse command-line arguments
  path: ^1.8.0      # To work with file paths
  yaml: ^3.1.0      # To read pubspec.yaml
  yaml_edit: ^2.0.0 # To safely modify pubspec.yaml

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  # Corrected the path to the main executable file
  flutter_packages_remover: bin/flutter_packages_remover.dart
