name: flutter_packages_remover
description: A command-line tool to find and remove unused packages from pubspec.yaml.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0 # To parse Dart code and find imports
  args: ^2.4.0      # To parse command-line arguments
  path: ^1.8.0      # To work with file paths
  yaml: ^3.1.0      # To read pubspec.yaml
  yaml_edit: ^2.0.0 # To safely modify pubspec.yaml

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
